name: Publish Java Base Image
trigger:
  branches:
    include:
      - refs/tags/*
pr: none

variables:
  acrName: hmctspublic
  targetRegistry: hmctspublic.azurecr.io
  serviceConnection: 'azurerm-prod'

jobs:
  - job:
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      maxParallel: 4
      matrix:
        openjdk-11-distroless:
          taskName: java-base-distroless-11
          dockerfile: Dockerfile
          version: "11"
        openjdk-11-distroless-debug:
          taskName: java-base-distroless-debug-11
          dockerfile: debug.Dockerfile
          version: "11"
        openjdk-17-distroless:
          taskName: java-base-distroless-17
          dockerfile: Dockerfile
          version: "17"
        openjdk-17-distroless-debug:
          taskName: java-base-distroless-debug-17
          dockerfile: debug.Dockerfile
          version: "17"
    steps:
      - task: AzureCLI@1
        displayName: 'Publish base image $(taskName)'
        inputs:
          azureSubscription: $(serviceConnection)
          scriptLocation: 'inlineScript'
          inlineScript: |
            az acr login --name $(acrName)
            VERSION_TAG=`git describe --tags`
            docker build --build-arg version=$(version) -t $(targetRegistry)/base/java:openjdk-$(version)-distroless-$VERSION_TAG -f distroless/$(dockerfile) distroless/
            docker push $(targetRegistry)/base/java:openjdk-$(version)-distroless-$VERSION_TAG
