name: cd

on:
  workflow_dispatch:
  push:
    branches: "master"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * TUE"

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        type: [distroless, distroless-debug]
        java: [11, 17]
    env:
      AZURE_CONTAINER_REGISTRY_URL: hmctspublic.azurecr.io
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Azure Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Build and Push - Node ${{ matrix.java }} ${{ matrix.type }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.type }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}/base/java:${{ matrix.java }}-${{ matrix.type }}
          build-args: |
            version=${{ matrix.java }}
