name: ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        type: [distroless, distroless-debug]
        java: [11, 17, 21]
    env:
      AZURE_CONTAINER_REGISTRY_URL: hmctspublic.azurecr.io
      URL: ${{ ${{ matrix.java }} == 21 && 'cgr.dev/chainguard/jdk' || 'hmctspublic.azurecr.io/imported/distroless/java${{ matrix.java }}' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Hadolint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./${{ matrix.type }}/Dockerfile
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Azure Container Repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push - Java ${{ matrix.java }} ${{ matrix.type }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.type }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}/base/java:pr-${{ matrix.java }}-${{ matrix.type }}
          build-args: |
            url= ${{ env.URL }}
